var a1 = 100;
console.log("type : ".concat(typeof a1, " value : ").concat(a1));
a1 = 'Vishal';
console.log("type : ".concat(typeof a1, " value : ").concat(a1));
var a2 = 100;
console.log("type : ".concat(typeof a2, " value : ").concat(a2));
a2 = 'Mahesh';
console.log("type : ".concat(typeof a2, " value : ").concat(a2));
var a3 = '100';
console.log("a3: type : ".concat(typeof a3, " value : ").concat(a3));
var a4 = a3;
console.log("a4 using Unknown : type : ".concat(typeof a4, " value : ").concat(a4));
var a5 = Number(a3);
console.log("a5 using Number() : type : ".concat(typeof a5, " value : ").concat(a5));
var a6 = parseInt(a3);
console.log("a6 using parseInt() : type : ".concat(typeof a6, " value : ").concat(a6));
var a7 = +a3;
console.log("a7 using + operator : type : ".concat(typeof a7, " value : ").concat(a7));
var a8 = Boolean(a3);
console.log("a8 using Boolean() : type : ".concat(typeof a8, " value : ").concat(a8));
